In [1]:
import numpy as np

In [38]:
a = np.array([[1,2,3],[4,5,6]])

In [85]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
A = np.sum(a**2,axis=1).reshape(2,1)

In [40]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
B = np.sum(b**2,axis=1).reshape(1,3)

In [95]:
B

array([[ 14,  77, 194]])

In [98]:
C = np.dot(a,b.T)

In [102]:
dist = A + B -2*C

In [106]:
dist

array([[  0,  27, 108],
       [ 27,   0,  27]])

In [114]:
np.argsort(dist[1])[0:2]

array([1, 0])

In [47]:
c = np.array([[1,2,3],[4,5,6],[10,11,12]])

In [49]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [48]:
b+c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [17, 19, 21]])

In [57]:
a1 = np.array([[1],[2]])

In [58]:
a1.shape

(2, 1)

In [54]:
a2 = np.array([[1,2]])

In [55]:
a2.shape

(1, 2)

In [59]:
a3 = np.array([1,2])

In [60]:
a3.shape

(2,)

In [61]:
b1 = np.array([[3],[4],[5]])

In [62]:
b1.shape

(3, 1)

In [63]:
b2 = np.array([[3,4,5]])

In [64]:
b2.shape

(1, 3)

In [65]:
b3 = np.array([3,4,5])

In [66]:
b3.shape

(3,)

In [67]:
a1 + b2

array([[4, 5, 6],
       [5, 6, 7]])

In [71]:
a1+b3

array([[4, 5, 6],
       [5, 6, 7]])

In [79]:
a1 + b1.T

array([[4, 5, 6],
       [5, 6, 7]])

In [81]:
(a3 + b1).T

array([[4, 5, 6],
       [5, 6, 7]])

In [84]:
a3 + b3.T

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [101]:
np.zeros(3)

array([0., 0., 0.])

In [146]:
a = np.array([3, 5, 9, 12, 34, 54,12])

In [140]:
b = np.array([2,3,5])

In [147]:
np.bincount(a)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [148]:
np.argmax(np.bincount(a))

12

In [149]:
a = np.arange(9)

In [169]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [170]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [171]:
c = np.array_split(a,3)

In [199]:
b = []

In [200]:
b.extend(c)

In [201]:
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [203]:
del(b[1])

In [204]:
b

[array([0, 1, 2]), array([6, 7, 8])]

In [197]:
np.concatenate(b)

array([0, 1, 2, 6, 7, 8])