In [1]:
import numpy as np

In [66]:
a = np.array([[1,2,7],[3,4,8],[5,6,9]])

In [67]:
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [68]:
b = np.array([0,1,2])

In [72]:
c = np.array([1,1,1])

In [73]:
b,c

(array([0, 1, 2]), array([1, 1, 1]))

In [74]:
a[b,c]

array([2, 4, 6])